-- Audit metadata baseline for idempotent warehouse batch processing.

CREATE TABLE IF NOT EXISTS audit.metadata_etl_batch (
    batch_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    release_id TEXT NOT NULL,
    pipeline_name TEXT NOT NULL DEFAULT 'warehouse_staging',
    batch_status TEXT NOT NULL DEFAULT 'STARTED'
        CHECK (batch_status IN ('STARTED', 'SUCCEEDED', 'FAILED', 'SKIPPED')),
    batch_started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    batch_completed_at TIMESTAMPTZ NULL,
    source_system TEXT NULL
        CHECK (
            source_system IS NULL OR source_system IN (
                'TLC_FILE',
                'LOOKUP_FILE',
                'HR_MYSQL',
                'FLEET_MONGODB',
                'DISPATCH_POSTGRES'
            )
        ),
    business_timezone TEXT NOT NULL DEFAULT 'America/New_York',
    audit_timezone TEXT NOT NULL DEFAULT 'UTC',
    input_parameters JSONB NOT NULL DEFAULT '{}'::jsonb,
    row_count_expected BIGINT NULL CHECK (row_count_expected IS NULL OR row_count_expected >= 0),
    row_count_loaded BIGINT NULL CHECK (row_count_loaded IS NULL OR row_count_loaded >= 0),
    error_message TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT metadata_etl_batch_completed_after_started
        CHECK (batch_completed_at IS NULL OR batch_completed_at >= batch_started_at)
);

CREATE INDEX IF NOT EXISTS ix_metadata_etl_batch_release_status
    ON audit.metadata_etl_batch (release_id, batch_status);

CREATE TABLE IF NOT EXISTS audit.metadata_source_extract (
    source_extract_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id UUID NOT NULL REFERENCES audit.metadata_etl_batch (batch_id),
    release_id TEXT NOT NULL,
    source_system TEXT NOT NULL
        CHECK (
            source_system IN (
                'TLC_FILE',
                'LOOKUP_FILE',
                'HR_MYSQL',
                'FLEET_MONGODB',
                'DISPATCH_POSTGRES'
            )
        ),
    source_entity TEXT NOT NULL,
    source_locator TEXT NOT NULL,
    source_extract_at TIMESTAMPTZ NOT NULL,
    extraction_mode TEXT NOT NULL DEFAULT 'FULL'
        CHECK (extraction_mode IN ('FULL', 'INCREMENTAL', 'REPLAY')),
    extraction_watermark TEXT NULL,
    source_checksum TEXT NULL,
    rows_extracted BIGINT NOT NULL DEFAULT 0 CHECK (rows_extracted >= 0),
    rows_loaded BIGINT NOT NULL DEFAULT 0 CHECK (rows_loaded >= 0),
    extract_status TEXT NOT NULL DEFAULT 'STARTED'
        CHECK (extract_status IN ('STARTED', 'SUCCEEDED', 'FAILED', 'SKIPPED')),
    error_message TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT metadata_source_extract_file_checksum_required
        CHECK (source_system NOT IN ('TLC_FILE', 'LOOKUP_FILE') OR source_checksum IS NOT NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_metadata_source_extract_identity
    ON audit.metadata_source_extract (
        batch_id,
        source_system,
        source_entity,
        source_locator,
        COALESCE(extraction_watermark, '')
    );

CREATE INDEX IF NOT EXISTS ix_metadata_source_extract_batch
    ON audit.metadata_source_extract (batch_id);

CREATE TABLE IF NOT EXISTS audit.metadata_file_checksum (
    file_checksum_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_id TEXT NOT NULL,
    source_system TEXT NOT NULL CHECK (source_system IN ('TLC_FILE', 'LOOKUP_FILE')),
    source_entity TEXT NOT NULL,
    source_file TEXT NOT NULL,
    checksum_algorithm TEXT NOT NULL DEFAULT 'SHA256',
    source_checksum TEXT NOT NULL,
    file_size_bytes BIGINT NULL CHECK (file_size_bytes IS NULL OR file_size_bytes >= 0),
    row_count BIGINT NULL CHECK (row_count IS NULL OR row_count >= 0),
    batch_id UUID NULL REFERENCES audit.metadata_etl_batch (batch_id),
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_metadata_file_checksum_release_file
    ON audit.metadata_file_checksum (
        release_id,
        source_system,
        source_entity,
        source_file,
        checksum_algorithm
    );

CREATE TABLE IF NOT EXISTS dq.dq_issue (
    dq_issue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id UUID NOT NULL REFERENCES audit.metadata_etl_batch (batch_id),
    release_id TEXT NOT NULL,
    source_system TEXT NOT NULL,
    source_entity TEXT NOT NULL,
    source_record_id TEXT NULL,
    rule_code TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'ERROR'
        CHECK (severity IN ('INFO', 'WARN', 'ERROR')),
    issue_message TEXT NOT NULL,
    issue_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    detected_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_dq_issue_batch_rule
    ON dq.dq_issue (batch_id, rule_code, severity);
