-- Source-aligned staging baseline.
-- Business timestamps preserve America/New_York local values as timestamp
-- without time zone. Audit timestamps use timestamptz and are produced in UTC.

CREATE TABLE IF NOT EXISTS staging.stg_tlc_green_trips (
    staging_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id UUID NOT NULL REFERENCES audit.metadata_etl_batch (batch_id),
    release_id TEXT NOT NULL,
    source_system TEXT NOT NULL DEFAULT 'TLC_FILE' CHECK (source_system = 'TLC_FILE'),
    source_entity TEXT NOT NULL DEFAULT 'tlc_green_tripdata',
    source_locator TEXT NOT NULL,
    source_record_id TEXT NOT NULL,
    source_file TEXT NOT NULL,
    source_row_number INTEGER NOT NULL CHECK (source_row_number >= 2),
    source_extract_at TIMESTAMPTZ NOT NULL,
    load_timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    source_checksum TEXT NOT NULL,
    extraction_watermark TEXT NULL,
    row_hash TEXT NOT NULL,
    vendor_id INTEGER NULL,
    lpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE NULL,
    lpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE NULL,
    store_and_fwd_flag TEXT NULL,
    ratecode_id INTEGER NULL,
    pu_location_id INTEGER NULL,
    do_location_id INTEGER NULL,
    passenger_count INTEGER NULL,
    trip_distance NUMERIC(12, 3) NULL,
    fare_amount NUMERIC(12, 2) NULL,
    extra NUMERIC(12, 2) NULL,
    mta_tax NUMERIC(12, 2) NULL,
    tip_amount NUMERIC(12, 2) NULL,
    tolls_amount NUMERIC(12, 2) NULL,
    ehail_fee NUMERIC(12, 2) NULL,
    improvement_surcharge NUMERIC(12, 2) NULL,
    total_amount NUMERIC(12, 2) NULL,
    payment_type INTEGER NULL,
    trip_type INTEGER NULL,
    congestion_surcharge NUMERIC(12, 2) NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_stg_tlc_green_trips_source_row
    ON staging.stg_tlc_green_trips (release_id, source_file, source_row_number);

CREATE INDEX IF NOT EXISTS ix_stg_tlc_green_trips_batch
    ON staging.stg_tlc_green_trips (batch_id);

CREATE INDEX IF NOT EXISTS ix_stg_tlc_green_trips_pickup
    ON staging.stg_tlc_green_trips (lpep_pickup_datetime);

CREATE TABLE IF NOT EXISTS staging.stg_lookup_vendor (
    staging_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id UUID NOT NULL REFERENCES audit.metadata_etl_batch (batch_id),
    release_id TEXT NOT NULL,
    source_system TEXT NOT NULL DEFAULT 'LOOKUP_FILE' CHECK (source_system = 'LOOKUP_FILE'),
    source_entity TEXT NOT NULL DEFAULT 'vendor',
    source_locator TEXT NOT NULL,
    source_record_id TEXT NOT NULL,
    source_file TEXT NOT NULL,
    source_row_number INTEGER NOT NULL CHECK (source_row_number >= 2),
    source_extract_at TIMESTAMPTZ NOT NULL,
    load_timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    source_checksum TEXT NOT NULL,
    extraction_watermark TEXT NULL,
    row_hash TEXT NOT NULL,
    vendor_id INTEGER NOT NULL,
    vendor_name TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_stg_lookup_vendor_source_row
    ON staging.stg_lookup_vendor (release_id, source_file, source_row_number);

CREATE UNIQUE INDEX IF NOT EXISTS ux_stg_lookup_vendor_business_key
    ON staging.stg_lookup_vendor (release_id, vendor_id);

CREATE TABLE IF NOT EXISTS staging.stg_lookup_taxi_zone (
    staging_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id UUID NOT NULL REFERENCES audit.metadata_etl_batch (batch_id),
    release_id TEXT NOT NULL,
    source_system TEXT NOT NULL DEFAULT 'LOOKUP_FILE' CHECK (source_system = 'LOOKUP_FILE'),
    source_entity TEXT NOT NULL DEFAULT 'taxi_zone',
    source_locator TEXT NOT NULL,
    source_record_id TEXT NOT NULL,
    source_file TEXT NOT NULL,
    source_row_number INTEGER NOT NULL CHECK (source_row_number >= 2),
    source_extract_at TIMESTAMPTZ NOT NULL,
    load_timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    source_checksum TEXT NOT NULL,
    extraction_watermark TEXT NULL,
    row_hash TEXT NOT NULL,
    location_id INTEGER NOT NULL,
    borough TEXT NOT NULL,
    zone TEXT NOT NULL,
    service_zone TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_stg_lookup_taxi_zone_source_row
    ON staging.stg_lookup_taxi_zone (release_id, source_file, source_row_number);

CREATE UNIQUE INDEX IF NOT EXISTS ux_stg_lookup_taxi_zone_business_key
    ON staging.stg_lookup_taxi_zone (release_id, location_id);

CREATE TABLE IF NOT EXISTS staging.stg_hr_drivers (
    staging_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id UUID NOT NULL REFERENCES audit.metadata_etl_batch (batch_id),
    release_id TEXT NOT NULL,
    source_system TEXT NOT NULL DEFAULT 'HR_MYSQL' CHECK (source_system = 'HR_MYSQL'),
    source_entity TEXT NOT NULL DEFAULT 'drivers',
    source_locator TEXT NOT NULL,
    source_record_id TEXT NOT NULL,
    source_extract_at TIMESTAMPTZ NOT NULL,
    load_timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    source_checksum TEXT NULL,
    extraction_watermark TEXT NULL,
    row_hash TEXT NOT NULL,
    driver_id TEXT NOT NULL,
    vendor_id INTEGER NOT NULL,
    driver_code TEXT NOT NULL,
    display_name TEXT NOT NULL,
    hire_date DATE NOT NULL,
    employment_status TEXT NOT NULL,
    license_status TEXT NOT NULL,
    license_expiry_date DATE NOT NULL,
    experience_years INTEGER NOT NULL CHECK (experience_years >= 0),
    home_borough TEXT NOT NULL,
    source_updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_stg_hr_drivers_business_key
    ON staging.stg_hr_drivers (release_id, driver_id);

CREATE TABLE IF NOT EXISTS staging.stg_hr_driver_changes (
    staging_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id UUID NOT NULL REFERENCES audit.metadata_etl_batch (batch_id),
    release_id TEXT NOT NULL,
    source_system TEXT NOT NULL DEFAULT 'HR_MYSQL' CHECK (source_system = 'HR_MYSQL'),
    source_entity TEXT NOT NULL DEFAULT 'driver_changes',
    source_locator TEXT NOT NULL,
    source_record_id TEXT NOT NULL,
    source_extract_at TIMESTAMPTZ NOT NULL,
    load_timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    source_checksum TEXT NULL,
    extraction_watermark TEXT NULL,
    row_hash TEXT NOT NULL,
    event_id TEXT NOT NULL,
    driver_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    effective_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    delivered_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    changes JSONB NOT NULL,
    is_late_arriving BOOLEAN NOT NULL,
    CONSTRAINT stg_hr_driver_changes_delivered_after_effective
        CHECK (delivered_at >= effective_at)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_stg_hr_driver_changes_business_key
    ON staging.stg_hr_driver_changes (release_id, event_id);

CREATE TABLE IF NOT EXISTS staging.stg_fleet_vehicles (
    staging_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id UUID NOT NULL REFERENCES audit.metadata_etl_batch (batch_id),
    release_id TEXT NOT NULL,
    source_system TEXT NOT NULL DEFAULT 'FLEET_MONGODB' CHECK (source_system = 'FLEET_MONGODB'),
    source_entity TEXT NOT NULL DEFAULT 'vehicles',
    source_locator TEXT NOT NULL,
    source_record_id TEXT NOT NULL,
    source_extract_at TIMESTAMPTZ NOT NULL,
    load_timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    source_checksum TEXT NULL,
    extraction_watermark TEXT NULL,
    row_hash TEXT NOT NULL,
    mongo_document_id TEXT NULL,
    vehicle_id TEXT NOT NULL,
    vendor_id INTEGER NOT NULL,
    plate_token TEXT NOT NULL,
    model_year INTEGER NOT NULL,
    vehicle_type TEXT NOT NULL,
    service_start_date DATE NOT NULL,
    vehicle_status TEXT NOT NULL,
    last_inspection_date DATE NOT NULL,
    source_updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_stg_fleet_vehicles_business_key
    ON staging.stg_fleet_vehicles (release_id, vehicle_id);

CREATE TABLE IF NOT EXISTS staging.stg_dispatch_shifts (
    staging_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id UUID NOT NULL REFERENCES audit.metadata_etl_batch (batch_id),
    release_id TEXT NOT NULL,
    source_system TEXT NOT NULL DEFAULT 'DISPATCH_POSTGRES' CHECK (source_system = 'DISPATCH_POSTGRES'),
    source_entity TEXT NOT NULL DEFAULT 'shifts',
    source_locator TEXT NOT NULL,
    source_record_id TEXT NOT NULL,
    source_extract_at TIMESTAMPTZ NOT NULL,
    load_timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    source_checksum TEXT NULL,
    extraction_watermark TEXT NULL,
    row_hash TEXT NOT NULL,
    shift_id TEXT NOT NULL,
    driver_id TEXT NOT NULL,
    vehicle_id TEXT NOT NULL,
    vendor_id INTEGER NOT NULL,
    shift_start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    shift_end TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    assigned_start_zone INTEGER NOT NULL,
    actual_end_zone INTEGER NOT NULL,
    trip_count INTEGER NOT NULL CHECK (trip_count >= 0),
    occupied_minutes NUMERIC(12, 2) NOT NULL CHECK (occupied_minutes >= 0),
    idle_minutes NUMERIC(12, 2) NOT NULL CHECK (idle_minutes >= 0),
    shift_status TEXT NOT NULL,
    CONSTRAINT stg_dispatch_shifts_end_after_start
        CHECK (shift_end >= shift_start)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_stg_dispatch_shifts_business_key
    ON staging.stg_dispatch_shifts (release_id, shift_id);

CREATE TABLE IF NOT EXISTS staging.stg_dispatch_trip_assignments (
    staging_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id UUID NOT NULL REFERENCES audit.metadata_etl_batch (batch_id),
    release_id TEXT NOT NULL,
    source_system TEXT NOT NULL DEFAULT 'DISPATCH_POSTGRES' CHECK (source_system = 'DISPATCH_POSTGRES'),
    source_entity TEXT NOT NULL DEFAULT 'trip_assignments',
    source_locator TEXT NOT NULL,
    source_record_id TEXT NOT NULL,
    source_extract_at TIMESTAMPTZ NOT NULL,
    load_timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    source_checksum TEXT NULL,
    extraction_watermark TEXT NULL,
    row_hash TEXT NOT NULL,
    trip_key TEXT NOT NULL,
    source_file TEXT NOT NULL,
    source_row_number INTEGER NOT NULL CHECK (source_row_number >= 2),
    driver_id TEXT NOT NULL,
    vehicle_id TEXT NOT NULL,
    shift_id TEXT NOT NULL,
    assignment_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    assignment_method TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_stg_dispatch_trip_assignments_trip_key
    ON staging.stg_dispatch_trip_assignments (release_id, trip_key);

CREATE UNIQUE INDEX IF NOT EXISTS ux_stg_dispatch_trip_assignments_source_row
    ON staging.stg_dispatch_trip_assignments (release_id, source_file, source_row_number);
