-- Data quality and quarantine executable DDL.
-- ERROR-level DQ records, including DQ_INVALID_ENUM, are stored in quarantine
-- tables and logged in dq.dq_issue by ETL code.

CREATE SCHEMA IF NOT EXISTS dq;

CREATE TABLE IF NOT EXISTS dq.dq_issue (
    dq_issue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id UUID NOT NULL REFERENCES audit.metadata_etl_batch (batch_id),
    release_id TEXT NOT NULL,
    source_system_code VARCHAR(50) NOT NULL
        REFERENCES nds.ref_source_system (source_system_code),
    source_entity TEXT NOT NULL,
    source_record_id TEXT NULL,
    rule_code TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'ERROR'
        CHECK (severity IN ('INFO', 'WARN', 'ERROR')),
    issue_message TEXT NOT NULL,
    issue_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    detected_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_dq_issue_batch_rule
    ON dq.dq_issue (batch_id, rule_code, severity);

CREATE TABLE IF NOT EXISTS dq.quarantine_record (
    quarantine_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id UUID NOT NULL REFERENCES audit.metadata_etl_batch (batch_id),
    release_id TEXT NOT NULL,
    source_system_code VARCHAR(50) NOT NULL
        REFERENCES nds.ref_source_system (source_system_code),
    source_entity TEXT NOT NULL,
    source_record_id TEXT NULL,
    source_file TEXT NULL,
    source_row_number INT NULL,
    error_rule_code TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'ERROR' CHECK (severity = 'ERROR'),
    raw_payload JSONB NOT NULL,
    quarantined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT quarantine_record_source_row_positive
        CHECK (source_row_number IS NULL OR source_row_number >= 2)
);

CREATE INDEX IF NOT EXISTS ix_quarantine_record_batch_rule
    ON dq.quarantine_record (batch_id, error_rule_code);

CREATE INDEX IF NOT EXISTS ix_quarantine_record_source
    ON dq.quarantine_record (source_system_code, source_entity);

CREATE TABLE IF NOT EXISTS dq.quarantine_stg_tlc_green_trips (
    quarantine_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id UUID NOT NULL REFERENCES audit.metadata_etl_batch (batch_id),
    release_id TEXT NOT NULL,
    error_rule_code TEXT NOT NULL,
    source_file TEXT NOT NULL,
    source_row_number INT NOT NULL CHECK (source_row_number >= 2),
    vendor_id TEXT NULL,
    lpep_pickup_datetime TEXT NULL,
    lpep_dropoff_datetime TEXT NULL,
    passenger_count TEXT NULL,
    trip_distance TEXT NULL,
    pu_location_id TEXT NULL,
    do_location_id TEXT NULL,
    fare_amount TEXT NULL,
    total_amount TEXT NULL,
    raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    quarantined_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_quarantine_tlc_batch_rule
    ON dq.quarantine_stg_tlc_green_trips (batch_id, error_rule_code);

CREATE TABLE IF NOT EXISTS dq.quarantine_stg_hr_drivers (
    quarantine_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id UUID NOT NULL REFERENCES audit.metadata_etl_batch (batch_id),
    release_id TEXT NOT NULL,
    error_rule_code TEXT NOT NULL,
    source_record_id TEXT NULL,
    driver_id TEXT NULL,
    vendor_id TEXT NULL,
    employment_status TEXT NULL,
    license_status TEXT NULL,
    raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    quarantined_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_quarantine_hr_drivers_batch_rule
    ON dq.quarantine_stg_hr_drivers (batch_id, error_rule_code);

CREATE TABLE IF NOT EXISTS dq.quarantine_stg_fleet_vehicles (
    quarantine_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id UUID NOT NULL REFERENCES audit.metadata_etl_batch (batch_id),
    release_id TEXT NOT NULL,
    error_rule_code TEXT NOT NULL,
    source_record_id TEXT NULL,
    vehicle_id TEXT NULL,
    vehicle_status TEXT NULL,
    vehicle_type TEXT NULL,
    raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    quarantined_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_quarantine_fleet_vehicles_batch_rule
    ON dq.quarantine_stg_fleet_vehicles (batch_id, error_rule_code);

CREATE TABLE IF NOT EXISTS dq.quarantine_stg_dispatch_shifts (
    quarantine_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id UUID NOT NULL REFERENCES audit.metadata_etl_batch (batch_id),
    release_id TEXT NOT NULL,
    error_rule_code TEXT NOT NULL,
    source_record_id TEXT NULL,
    shift_id TEXT NULL,
    driver_id TEXT NULL,
    vehicle_id TEXT NULL,
    shift_start TEXT NULL,
    shift_end TEXT NULL,
    shift_status TEXT NULL,
    raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    quarantined_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_quarantine_dispatch_shifts_batch_rule
    ON dq.quarantine_stg_dispatch_shifts (batch_id, error_rule_code);
